# Generated by Django 2.2.6 on 2019-10-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gowedoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
